[package]
name = "paxos"
version = "0.2.0"
authors = ["whfuyn <whfuyn@outlook.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
bytes = "0.4.12"
serde = { version = "1.0.113", features = ["derive"] }
bincode = "1.2.1"